### ISSUE TITLE
运行示例闪退

### ISSUE THREAD

**Issue by Lepinr** [lesliesam/react-native-wheel-picker#10]
react-native 0.32.0
android 4.4.4

<pre><code>
09-13 10:03:39.706 30024-30024/com.alibaba.jiwu E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: com.alibaba.jiwu, PID: 30024
                                                            java.lang.NoSuchMethodError: com.facebook.react.uimanager.events.Event.<init>
                                                                at com.zyu.ItemSelectedEvent.<init>(ReactWheelCurvedPicker.java:90)
                                                                at com.zyu.ReactWheelCurvedPicker$1.onWheelSelected(ReactWheelCurvedPicker.java:43)
                                                                at com.aigestudio.wheelpicker.core.AbstractWheelPicker.onWheelSelected(AbstractWheelPicker.java:331)
                                                                at com.aigestudio.wheelpicker.view.WheelCrossPicker.confirmData(WheelCrossPicker.java:147)
                                                                at com.aigestudio.wheelpicker.view.WheelCrossPicker.run(WheelCrossPicker.java:125)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                at dalvik.system.NativeStart.main(Native Method)
</code></pre>

**Comment by lesliesam** [comment]
Issue resolved, please try the latest version. Since the constructor of com.facebook.react.uimanager.events.Event has changed in RN 0.32. The timestampMs parameter no longer exists.
